# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrthancCli < Formula
  desc "A powerful command-line interface for managing Orthanc DICOM servers"
  homepage "https://github.com/proencaj/orthanc-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.2/orthanc-cli-0.2.2-darwin-amd64.tar.gz"
      sha256 "9a9ab1e40713b0edca124186e52655b078bc0e4ff5b10270e2ee1ee30731a2b8"

      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.2/orthanc-cli-0.2.2-darwin-arm64.tar.gz"
      sha256 "316bcd6436d98672be030cf9a02d45e31f432bca556cf21c4346e71364772c9f"

      def install
        bin.install "orthanc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.2/orthanc-cli-0.2.2-linux-amd64.tar.gz"
      sha256 "da18d3e9cc2c4e0e77468de68ae473924b3233fda12116e3aba73453da2b2d77"
      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.2/orthanc-cli-0.2.2-linux-arm64.tar.gz"
      sha256 "9ce5cf19f060cf826d12d38a5ab7736e533b060643be2274bf4f3b51c0b47bcf"
      def install
        bin.install "orthanc"
      end
    end
  end

  test do
    system "#{bin}/orthanc", "--version"
  end
end
