# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrthancCli < Formula
  desc "A powerful command-line interface for managing Orthanc DICOM servers"
  homepage "https://github.com/proencaj/orthanc-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.1/orthanc-cli-0.2.1-darwin-amd64.tar.gz"
      sha256 "a7ba23b08bb8e4d3806c4cbf93b2fe0132be0d12c596dd4d9d5ecc42f5eeed9a"

      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.1/orthanc-cli-0.2.1-darwin-arm64.tar.gz"
      sha256 "aaf6d88e6a728b34e52adaafb7c9b326d20d23ff7d715032d6014ef30da3c395"

      def install
        bin.install "orthanc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.1/orthanc-cli-0.2.1-linux-amd64.tar.gz"
      sha256 "9d2aa9b4a6369f0265f69b230dc1503039a03332a262d37a2d90b03b81ecf52e"
      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.1/orthanc-cli-0.2.1-linux-arm64.tar.gz"
      sha256 "b718a89763008a17372d83c22754a74b0b336cd6feb39b17c076e504d127d98a"
      def install
        bin.install "orthanc"
      end
    end
  end

  test do
    system "#{bin}/orthanc", "--version"
  end
end
