# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrthancCli < Formula
  desc "A powerful command-line interface for managing Orthanc DICOM servers"
  homepage "https://github.com/proencaj/orthanc-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.0/orthanc-cli-0.2.0-darwin-amd64.tar.gz"
      sha256 "2e4943e0e27eb707319f0a435430fee3785e1a72fb72ca60954806c28045a334"

      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.0/orthanc-cli-0.2.0-darwin-arm64.tar.gz"
      sha256 "ec1c209b2a08ecff356183eefd25d5e14132bc1c44810a72f4b1ad3a308c9ff1"

      def install
        bin.install "orthanc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.0/orthanc-cli-0.2.0-linux-amd64.tar.gz"
      sha256 "c0be256c0c09cbd036c9e3f181f4bd82518aa85f81b3e273eb38eefbdfe3b6b1"
      def install
        bin.install "orthanc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/proencaj/orthanc-cli/releases/download/v0.2.0/orthanc-cli-0.2.0-linux-arm64.tar.gz"
      sha256 "6f7a9e2bc529a58111a5af7074f2a3aa46e389ad554c4f44c43617dbe59bd7ca"
      def install
        bin.install "orthanc"
      end
    end
  end

  test do
    system "#{bin}/orthanc", "--version"
  end
end
